#!/bin/bash

# Script to compile the Java source files into class files and then run them from a fixed directory

javac -d ./Other/out/production/hw01/xyes ./Other/src/xyes/Util.java ./Other/src/xyes/Xyes.java
java -cp ./Other/out/production/hw01/xyes xyes.Xyes "$@"
