package xyes;

import java.util.Arrays;

/**
 * Class containing the code relevant to the xyes program, which is a generalization of the 'yes'
 * *nix command.
 */
public class Xyes {

  /**
   * Main function of the class. Displays string generated by the concatenation of all arguments an
   * infinite number of times, unless the first argument is '-limit', in which case it is only
   * printed 20 times. Additionally, in the case that there are no arguments, 'hello world' is used
   * as the string to print.
   *
   * @param args The input arguments to the function.
   */
  public static void main(String[] args) {
    String out;
    boolean limit;
    Util util = new Util();

    // Determine output string and whether or not the outputs are limited from inputs
    if (args.length == 0) {
      out = "hello world";
      limit = false;
    } else if (args[0].equals("-limit")) {
        if (args.length == 1) {
            out = "hello world";
            limit = true;
        } else {
            out = util.concat(Arrays.copyOfRange(args, 1, args.length));
            limit = true;
        }
    } else {
      out = util.concat(args);
      limit = false;
    }

    if (limit) {
      for (int i = 0; i < 20; i++) {
        System.out.println(out);
      }
    } else {
      while (true) {
        System.out.println(out);
      }
    }
  }

}
