#!/bin/bash
APACHE="/usr/share/java/apache-commons-net.jar"
GSON="./Other/dep/gson-2.8.6.jar"

# Script to compile the Java source files into class files and then run them from a fixed directory

javac -d ./Other/out/ -cp $GSON:$APACHE ./Other/src/xtcp/xtcp.java
java -cp $GSON:$APACHE:./Other/out/ xtcp.xtcp "$@"
