package xtcp;

import io.netty.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonStreamParser;

import java.util.ArrayList;
import java.util.Scanner;

/**
 * Class to contain the functionality of the xtcp program.
 */
public class xtcp {
    private static JsonObject out1;
    private static JsonArray out2;    

    /**
     * Main function of xtcp. Waits for TCP client connection and 
     * receives and responds with JSON.
     * @args arguments to the main function of xtcp.
     */
    public static void main(String[] args) {
        int portNo = 4567;

        // Validate arguments
        if (args.length != 1) {
            System.out.println("Usage: ./xtcp <port number>");
            System.exit(1);
        }
        
        try {
            Integer.parseInt(args[0]);
        } catch (NumberFormatException e) {
            System.out.println("Usage: ./xtcp <port number>");
            System.exit(2);
        }

        portNo = Integer.parseInt(args[0]);
        if (portNo <= 0) {
            System.out.println("Usage: ./xtcp <port number>");
            System.exit(3);
        }

        // Set up TCP connection 
        
        // Do some JSON parsing
        parseInput();

        // Debug: print JSON
        System.out.println(out1.toString());
        System.out.println(out2.toString());
    }

    /**
     * Helper method to parse all JSON input from the a TCP input stream
     * and create the appropriate JSON objects to return.
     */
    private static void parseInput() {
        // Open a scanner to accept all the JSON values from TCP conn
        // into one string to give to a parser
        Scanner input = new Scanner(System.in);
        StringBuilder rawJson = new StringBuilder();
        while (input.hasNextLine()) {
            rawJson.append(input.nextLine());
            rawJson.append("\n");
        }
        
        input.close();
        String jsonInput = rawJson.toString();

        // Create a Gson object to convert JSON into Java objects
        Gson gson = new GsonBuilder().create();
        // Open a parser taking the String generated by inputs into STDIN
        JsonStreamParser parser = new JsonStreamParser(jsonInput);

        int jsonValues = 0;
        ArrayList<JsonElement> jElements = new ArrayList<>();

        // As long as input is available on the parser,
        // interact with each JSON value
        while (parser.hasNext()) {
            JsonElement element = parser.next();
            jsonValues++;
            jElements.add(element);
        }
        
        // Generate the JSON list from the individual 
        // JSON elements in the ArrayList we obtained
        JsonArray out1array = new JsonArray();
        for (JsonElement e : jElements) {
            out1array.add(e);
        }

        // Create the first output, a JSON object
        out1 = new JsonObject();
        // add "count", (# of values read)
        out1.add("count", new JsonPrimitive(jsonValues));
        // add "seq", (array of JSON values in order)
        out1.add("seq", out1array);

        // Create the second output, a JSON array
        out2 = new JsonArray();
        // add first element - number of JSON values read
        out2.add(jsonValues);
        // add remaining elements - sequence of JSON values in reverse order
        for (int i = jElements.size() - 1; i >= 0; i--) {
            out2.add(jElements.get(i));
        }
    }
}
